### ISSUE TITLE
Add Event support for Subscription Order Statuses 

### ISSUE THREAD

**Issue by raamdev** [websharks/woocommerce-intercom-pro#1]
@jaswsinc writes...

> If the shop owner is also running the WooCommerce Subscriptions extension, then you have 'Subscriptions' statuses to deal with also, which are different from Order statuses. For this reason, my suggestion would be to work through Orders first and get those just the way you want them. Then at some point in the future when you have more time to test Subscriptions extensively, you can take a look at all of the possible Subscription statuses.

**Comment by jaswrks** [comment]
Referencing my research on Order statuses and the comments that I left here in code.
https://github.com/websharks/woocommerce-s2member-x-pro/blob/160801.34929/src/includes/classes/Utils/OrderStatus.php#L146

For Subscriptions, see: https://github.com/websharks/woocommerce-s2member-x-pro/blob/160801.34929/src/includes/classes/Utils/OrderStatus.php#L175

**Comment by jaswrks** [comment]
Referencing KBA draft: https://wpsharks.com/?post_type=kb_article&p=3092&preview=true

Support has been added for all WooCommerce events:

## Orders (of any Type, excluding `shop_subscription`)
- ~~`order-draft`~~ excluded intentionally.
- ~~`order-pending`~~ excluded intentionally.
- `order-processing`
- `order-completed`
- `order-on-hold`
- `order-cancelled`
- `order-refunded`
- `order-failed`
- _And others added by WooCommerce extensions._

## Subscriptions (Specifically for `shop_subscription` Type)
- ~~`subscription-draft`~~ excluded intentionally.
- ~~`subscription-pending`~~ excluded intentionally.
- `subscription-active`
- `subscription-on-hold`
- `subscription-cancelled`
- `subscription-switched`
- `subscription-expired`
- `subscription-pending-cancel`
- _And others added by WooCommerce extensions._

**Comment by jaswrks** [comment]
Next Release Changelog:
- **Compatibility:** This release adds compatibility with WooCommerce Subscriptions. See [Issue #1](https://github.com/websharks/woocommerce-intercom-pro/issues/1).
- **Compatibility:** This release adds support for all WooCommerce Order and/or Subscription status changes, including those added by WooCommerce extensions such as the WooCommerce Give Order extension. See [Issue #1](https://github.com/websharks/woocommerce-intercom-pro/issues/1).

**Comment by jaswrks** [comment]
Tagging as partial completion. Pending review by @raamdev and publication of [this KBA](https://wpsharks.com/?post_type=kb_article&p=3092&preview=true).

**Comment by raamdev** [comment]
@jaswsinc Could you clarify what additional work is necessary here? If completion of this issue is just pending a review from me, there's no need to add the `partial completion` label.

**Comment by jaswrks** [comment]
Just to publish the KBA. The KBA is referenced by the plugin with this update, so I tagged this issue to help as a reminder that it needs to be published before the issue can be closed. However, if you'd rather I not use the label for that it's with me.

**Comment by raamdev** [comment]
@jaswsinc No problem. That's a good use for that tag, yes. Please continue to do that if there's some other work that needs to be completed before the release that the issue is attached to. 👍

**Comment by renzms** [comment]
### Tested

See comment [here](https://github.com/websharks/woocommerce-intercom-pro/issues/19#issuecomment-263283122)

**Comment by jaswrks** [comment]
@raamdev writes...

> That's a good use for that tag, yes.

Copy that.

**Comment by jaswrks** [comment]
@renzms writes...

> See comment here

That was a bug. Thanks for catching. Referencing: https://github.com/websharks/woocommerce-intercom-pro/issues/19#issuecomment-263398460

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Possible Bug

For Subscriptions, it seems to be creating 2 orders. 1 for `Subscription` and 1 set as an `Order`.

In the testing, in Intercom Order 224 is counted as the Ordered Product and Order 225 is counted as the Subscription

On the backend however in WooCommerce, the Subscription counts as one product, Order 224:

![screen shot 2016-11-30 at 7 15 38 am](https://cloud.githubusercontent.com/assets/13220018/20733341/caf5c832-b6cd-11e6-871e-4464f21df345.png)


When Subscription is On-Hold:
![screen shot 2016-11-30 at 7 19 48 am](https://cloud.githubusercontent.com/assets/13220018/20733275/677f3c16-b6cd-11e6-9f9d-d21daa72811c.png)

When Subscription is Processing (notice Subscription says active):

![screen shot 2016-11-30 at 7 20 31 am](https://cloud.githubusercontent.com/assets/13220018/20733293/8e50ce0e-b6cd-11e6-9ff9-d201cfc86632.png)


When Subscription is Completed or is Refunded (only shows up as Order 224 and as an `Order`):

![screen shot 2016-11-30 at 7 23 24 am](https://cloud.githubusercontent.com/assets/13220018/20733359/ebf35a54-b6cd-11e6-9ae6-82cadb6fb46d.png)

When Subscription is Canceled:

![screen shot 2016-11-30 at 7 25 16 am](https://cloud.githubusercontent.com/assets/13220018/20733415/310aa570-b6ce-11e6-9c29-fd17ecac38e4.png)

**Comment by jaswrks** [comment]
@renzms I have confirmed that the above behavior is correct in all cases. It looks like a bug, but it's actually the intended behavior. Any given order can contain a subscription + something more. Internally, both are orders, but it's important for sites who sell subscriptions to know the status of both the order and also of a subscription that results from an order status changing.

What I did change in the last set of tweaks however, is that I'm now displaying the `ORDER_NUMBER` as `ORDER_ID` and instead of showing `ORDER_ID` for subscriptions, it now shows `SUBSCRIPTION_ID` to help make this a bit clearer; i.e., look less like a duplicate.

![2016-12-03_06-31-00](https://cloud.githubusercontent.com/assets/1563559/20860496/d03dfd1e-b925-11e6-9a73-2e03af412712.png)

**Comment by renzms** [comment]
@jaswsinc 

Hi Jason! Which branch is the update on? The latest version of: https://github.com/websharks/woocommerce-intercom-pro/tree/release/161124.6961-RC or is there another bleeding edge version?

It hasn't updated on my end while using the latest RC: 
![screen shot 2016-12-06 at 12 00 45 am](https://cloud.githubusercontent.com/assets/13220018/20891899/1d3cd248-bb47-11e6-9bc1-4f98946ecb33.png)

**Comment by renzms** [comment]
@jaswsinc 

Scratch that last comment above ^ :)

Looks like it updated after I updated the WP Sharks Core and refreshed the page, as well as Intercom Dashboard.


![screen shot 2016-12-06 at 12 08 30 am](https://cloud.githubusercontent.com/assets/13220018/20892292/83e2d802-bb48-11e6-9b06-ff393168b1e1.png)


@raamdev Looks good to me! 👍

**Comment by raamdev** [comment]
Updated this KB Article with a new screenshot: 
https://wpsharks.com/kb-article/woocommerce-intercom-pro/intercom-event-names

**Comment by jaswrks** [comment]
Awesome. Thanks for the testing! :-) Much appreciated.

**Comment by raamdev** [comment]
**WooCommerce Intercom Pro v161209.85885** has been released and includes changes from this GitHub Issue. See the [changelog](https://wpsharks.com/product/woocommerce-intercom-pro/changelog) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#1).
