### ISSUE TITLE
TODO: Create a plugin option that lets you define the scenarios where the widget should be loaded.

### ISSUE THREAD

**Issue by jaswrks** [websharks/woocommerce-intercom-pro#12]
Referencing: https://github.com/websharks/woocommerce-intercom-pro/blob/160909.7530/src/includes/classes/Utils/JsSnippet.php#L48

**Comment by jaswrks** [comment]
A filter = 1 story point.

**Comment by jaswrks** [comment]
- **New Filter:** `add_filter('woocommerce_intercom_js_snippet_enable', '__return_false');` to disable the JS snippet selectively.

**Comment by jaswrks** [comment]
Reopening. This is a partial completion.

**Comment by raamdev** [comment]
> Reopening. This is a partial completion.

Still 1 story point here?

**Comment by jaswrks** [comment]
Looking at this again I think a filter is all that's needed here and we have already done that. Do you agree that a filter is adequate for this or do you have something else in mind?

**Comment by raamdev** [comment]
Hmm, I was thinking this would look like a list of checkboxes where you could enable/disable the widget on certain pages. For example:
- Home Page
- Single Posts
- Single Pages
- Category Archive Views
- Tag Archive Views
- Custom Post Types [lists any CPTs that have been registered]

Thinking about this a bit more, it might be useful to even have a URI Exclusions Panel where a site owner could define a list of exclusions.

My thinking here is that a site owner might not want the Intercom Widget to appear on _every single page_ of their site. For example, they may have a WooCommerce Store section of their site, where the Intercom widget is applicable. But the rest of their site — the Home Page, the Blog (and all associated Posts and post archive views) — they might not want the Intercom widget to appear.

**Comment by jaswrks** [comment]
Next Release Changelog:
- **New Feature:** Adding support for URI Inclusion patterns. See [Issue #12](https://github.com/websharks/woocommerce-intercom-pro/issues/12).
- **New Feature:** Adding support for URI Exclusion patterns. See [Issue #12](https://github.com/websharks/woocommerce-intercom-pro/issues/12).

![2016-11-19_08-41-03](https://cloud.githubusercontent.com/assets/1563559/20457270/fa5780c2-ae33-11e6-82ad-b5e364670368.png)

**Comment by renzms** [comment]
@raamdev 

### Feature confirmed as working.

Tested using:
- **WP Sharks Core Version 161026.47592**
- **WooCommerce Intercom Pro Version 161124.6961-RC**
- **WooCommerce Version 2.6.8**


Tested Inclusions/Exclusions:
- using direct file paths
- using WRegx and and Advanced WRegx from samples in [KBA](https://wpsharks.com/kb-articles/wregx)
- using combinations of Inclusions and/or Exclusions, (if the Exclusion URI somehow overlaps with the Inclusion URI using WRegx, the Exclusion pattern is the one that is followed)
- using multi-line Inclusion/Exclusions

May I suggest to include in the documentation or article that `^/$`, means homepage, as it might be helpful for users. Also, our other plugins included a note like the following:

```Note: please remember that your entries here should be formatted as a line-delimited list; e.g., one exclusion pattern per line.```

That might be helpful also for users to know for the Inclusion/Exclusions in case they want to be very specific about the pages.


No bugs here 👍

**Comment by jaswrks** [comment]
> Note: please remember that your entries here should be formatted as a line-delimited list; e.g., one exclusion pattern per line.

I agree we should add a note about this.

**Comment by jaswrks** [comment]
Noted added.

**Comment by jaswrks** [comment]
Additional changelog entry:

- **New Feature:** It is now possible to configure the Intercom Messenger icon display settings so that it's only shown to logged-in users, only to logged-out users, or to everyone (default behavior). See: **Dashboard → WooCommerce → Intercom → Messenger Display Options**.

![2016-12-03_06-49-36](https://cloud.githubusercontent.com/assets/1563559/20860432/af3d76f4-b924-11e6-99ed-0063e1f37cf0.png)

**Comment by renzms** [comment]
@jaswsinc 

The **Logged-In User Status** feature is currently not working for me in the latest RC test.

Regardless of whether the user is logged-in/logged-out and the settings chosen for the feature, the Intercom messenger appears on the front end.

`Show only to logged-out Users` **is showing to logged-in User**

>![screen shot 2016-12-06 at 12 33 16 am](https://cloud.githubusercontent.com/assets/13220018/20893149/ae211752-bb4b-11e6-88b1-604461e1afc4.png)
>![screen shot 2016-12-06 at 12 33 38 am](https://cloud.githubusercontent.com/assets/13220018/20893148/ae1e3438-bb4b-11e6-8481-a1401f1016c6.png)


______



`Show only to logged-in Users`  **is showing to logged-out User**
>![screen shot 2016-12-06 at 12 32 54 am](https://cloud.githubusercontent.com/assets/13220018/20893151/ae2ad224-bb4b-11e6-998a-bde69138352f.png)
>![screen shot 2016-12-06 at 12 33 01 am](https://cloud.githubusercontent.com/assets/13220018/20893285/382f224a-bb4c-11e6-9df7-c49257ed5709.png)



**Positive note, the `URI Exclusion/Inclusion` is still working fine** 👍

**Comment by renzms** [comment]
@raamdev @jaswsinc 

Links to KBAs redirect properly to `https://wpsharks.com/kb/[product]` or `https://wpsharks.com/kb-articles/`.

The link to `Intercom Acquire` goes first to https://wpsharks.com/r/intercom-acquire and then https://www.intercom.com/live-chat, is this correct?

**Comment by jaswrks** [comment]
> The link to Intercom Acquire goes first to https://wpsharks.com/r/intercom-acquire and then https://www.intercom.com/live-chat, is this correct?

That looks right to me, yes.

**Comment by jaswrks** [comment]
@raamdev @renzms The bug with logged-in/out has been fixed now. Thanks for catching that!

**Comment by renzms** [comment]
> The bug with logged-in/out has been fixed now.

@jaswsinc @raamdev 

### Fix confirmed as working for all options of *Logged-In User Status*

All good here on my end 👍

**Comment by raamdev** [comment]
**WooCommerce Intercom Pro v161209.85885** has been released and includes changes from this GitHub Issue. See the [changelog](https://wpsharks.com/product/woocommerce-intercom-pro/changelog) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#12).
