### ISSUE TITLE
Bug: Incorrect Decimal

### ISSUE THREAD

**Issue by jaswrks** [websharks/woocommerce-intercom-pro#17]
Intercom recorded `1.03`.

![2016-09-24_01-44-04](https://cloud.githubusercontent.com/assets/1563559/18807623/8753a04a-81f8-11e6-8984-57f6e9440e4e.png)

The actual sale amount recorded by WooCommerce was `103.20`
![2016-09-24_01-44-29](https://cloud.githubusercontent.com/assets/1563559/18807624/876d17dc-81f8-11e6-96ed-df75844e8d0a.png)

**Comment by jaswrks** [comment]
According to the docs...
https://developers.intercom.io/reference#event-metadata-types

> `amount` key is a positive integer representing the amount in **cents**.

**Comment by jaswrks** [comment]
- **Bug Fix:** In the Event API calls, `amount` must be given in **cents** (i.e., total x 100) for proper calculation on the Intercom side. Closes [this GitHub issue](https://github.com/websharks/woocommerce-intercom-pro/issues/17).

**Comment by jaswrks** [comment]
Fix confirmed. My last order has the correct subtotal.

![2016-09-24_02-11-43](https://cloud.githubusercontent.com/assets/1563559/18807825/ff9aec66-81fd-11e6-95ba-5406e10bb493.png)

**Comment by renzms** [comment]
@raamdev 

### Fixed confirmed as working.

Tested using:
- **WP Sharks Core Version 161026.47592**
- **WooCommerce Intercom Pro Version 161124.6961-RC**
- **WooCommerce Version 2.6.8**

No bugs here 👍 

![screen shot 2016-11-28 at 8 55 34 pm](https://cloud.githubusercontent.com/assets/13220018/20669342/b1920ee8-b5ae-11e6-86e0-a8dbe4941db2.png)
![screen shot 2016-11-28 at 8 55 26 pm](https://cloud.githubusercontent.com/assets/13220018/20669386/dbf26728-b5ae-11e6-9e1f-b9d5c18b8184.png)

**Comment by raamdev** [comment]
**WooCommerce Intercom Pro v161209.85885** has been released and includes changes from this GitHub Issue. See the [changelog](https://wpsharks.com/product/woocommerce-intercom-pro/changelog) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#17).
