### ISSUE TITLE
Enhancement: Improve Event Names

### ISSUE THREAD

**Issue by jaswrks** [websharks/woocommerce-intercom-pro#19]
The current event name for an order being received (which follows the advice to use `verb`-`noun` as suggested by Intercom API docs) is `placed-order`. This works well because it follows the idea of this being 'Their Activity'; i.e., the reason for a `verb-` prefix.

![2016-09-24_02-11-43](https://cloud.githubusercontent.com/assets/1563559/18807764/4310eb50-81fc-11e6-8af6-dcfba28cfdf3.png)

However, we are listening for both `processing` and `completed` status changes, and potentially others in the future. As it stands now, there are going to be duplicate events (same order, same event name, back-to-back) posted to Intercom whenever this is running on a site that _does_ implement a `processing` phase.

Instead of `placed-order`, we could do something that is WooCommerce-specific, such as: `order-[status]` and `subscription-[status]`. That would allow for additional statuses to be tracked later as well, without needing to use a different naming scheme. For example, it might be nice to add an `order-refunded` status event, or `order-on-hold`.

That doesn't work quite as well with the idea of this being 'Their Activity' though, because the leading verb is dropped. However, it does seem to me like a more informative approach given that what seems most important is to see the customer's activity as it relates to WooCommerce order statuses.

@raamdev Thoughts on this?

**Comment by jaswrks** [comment]
Referencing a list of standard order statuses in WooCommerce.

```
/*
         * - `draft` When an order is still in the draft phase.
         *
         * - `pending` Order received (unpaid). e.g., abandoned orders have this status also.
         *
         * - `processing` Payment received & stock reduced. Awaiting review/fulfillment.
         *
         * - `on-hold` Stock is reduced. Awaiting payment.
         *
         * - `completed` Order fulfilled and complete.
         *
         * - `cancelled` Cancelled by an admin or the customer.
         *
         * - `refunded` Refunded by an admin or via a payment gateway notification.
         *
         * - `failed` Payment failed or was declined (unpaid). Note that this status may not show
         *            immediately and instead show as pending until verified (e.g., PayPal).
         */
```

**Comment by raamdev** [comment]
> That doesn't work quite as well with the idea of this being 'Their Activity' though, because the leading verb is dropped. However, it does seem to me like a more informative approach given that what seems most important is to see the customer's activity as it relates to WooCommerce order statuses.

I agree. I'd go with `order-[woocommerce-order-status]`.

We should then document the above list of WooCommerce statuses in the WooCommerce Intercom docs so that site owners know what those various statuses mean when they see them inside Intercom.

**Comment by jaswrks** [comment]
Next Release Changelog:
- Standardizing Event names sent to Intercom. New format: `order-[status]`. See [Issue #19](https://github.com/websharks/woocommerce-intercom-pro/issues/19).

**Comment by jaswrks** [comment]
_Noting that only two Order statuses are recorded at this time: `processing` and `completed`_
- `order-processing`
- `order-completed`

**Comment by jaswrks** [comment]
_Potentially some other statuses once https://github.com/websharks/woocommerce-intercom-pro/issues/1 is completed._

**Comment by jaswrks** [comment]
Setting as `partial-completion`; pending KBA suggested in https://github.com/websharks/woocommerce-intercom-pro/issues/19#issuecomment-249628606

**Comment by jaswrks** [comment]
KBA drafted: https://wpsharks.com/?post_type=kb_article&p=3092&preview=true

**Comment by jaswrks** [comment]
Support has been added for all WooCommerce events. See: https://github.com/websharks/woocommerce-intercom-pro/issues/1#issuecomment-261731737

**Comment by renzms** [comment]
@raamdev  @jaswsinc 

Should it say: **[order]/[subscription] +`WooCommerce status/event`**?

Currently in Intercom it is only showing the `WooCommerce status/event`

![screen shot 2016-11-28 at 10 20 14 pm](https://cloud.githubusercontent.com/assets/13220018/20671658/2e277448-b5b9-11e6-8ec4-88b6ebc1df80.png)



Tested using:
- **WP Sharks Core Version 161026.47592**
- **WooCommerce Intercom Pro Version 161124.6961-RC**
- **WooCommerce Version 2.6.8**

**Comment by raamdev** [comment]
@renzms That looks correct to me. Jason can correct me if I'm wrong, but I think it should exclude the the `order-` and `subscription-` prefix. 

I'm adding a screenshot to the [associated KB article](https://wpsharks.com/kb-article/woocommerce-intercom-pro/intercom-event-names) to help clarify what those events will look like on the Intercom side.

**Comment by jaswrks** [comment]
@renzms Thank you for catching this.

@renzms @raamdev Yes, it should have the `order-` and `subscription-` prefix. That was an error on my part and it has now been corrected in the RC and dev branch.

**Comment by raamdev** [comment]
@jaswsinc Thanks!

@renzms Could you please re-test and take a new screenshot for me? I'd like to update the screenshot I added [here](https://wpsharks.com/kb-article/woocommerce-intercom-pro/intercom-event-names).

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Confirmed as working in latest build

Now has the `order-` prefix 👍 

![screen shot 2016-11-29 at 12 09 23 pm](https://cloud.githubusercontent.com/assets/13220018/20696420/d941916a-b62c-11e6-8f69-1bd12da71eb9.png)

**Comment by jaswrks** [comment]
@renzms Thanks! If it's not too much trouble, would it be possible for you to cut a screenshot that has the statuses in a more typical order please?

- `order-on-hold`
- `order-processing`
- `order-completed`
- `order-refunded`

**Comment by jaswrks** [comment]
Or am I just reading it in reverse and that's what you did?

**Comment by renzms** [comment]
> Or am I just reading it in reverse and that's what you did?

@jaswsinc 

Hi Jason, in the original screenshot, it's actually 4 different orders and Intercom displays the latest Order Update Status first. 😃  

So if you were to have 1 order go through the following updates:

- 1. On-hold
- 2. Processing
- 3. Completed
- 4. Order refunded

it would appear in the feed in Intercom in reverse order:

- `order-refunded`
- `order-completed`
- `order-processing`
- `order-on-hold`

I did however create a screenshot that has it in a typical order using 1 Order number if you'd like to use that for the KBA:

![screen shot 2016-11-29 at 1 50 10 pm](https://cloud.githubusercontent.com/assets/13220018/20698372/9e5e15e6-b63b-11e6-9d1f-a914befc502d.png)

**Comment by jaswrks** [comment]
I see. Thanks for explaining that. Makes sense to me now :-)

**Comment by raamdev** [comment]
**WooCommerce Intercom Pro v161209.85885** has been released and includes changes from this GitHub Issue. See the [changelog](https://wpsharks.com/product/woocommerce-intercom-pro/changelog) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#19).
