### ISSUE TITLE
Update to use Personal Access Tokens (API Keys being deprecated)

### ISSUE THREAD

**Issue by raamdev** [websharks/woocommerce-intercom-pro#20]
Intercom is switching from API Keys to Personal Access Tokens:

> If you are currently using API Keys, you will need to switch these to Personal Access Tokens by January 2017 - read more about API Key deprecation here.

https://developers.intercom.com/docs/personal-access-tokens

We need to update the WooCommerce Intercom plugin to support personal access tokens. I'm not sure if there's anything more needed than simply changing the wording and the link in the inline documentation.

**Comment by jaswrks** [comment]
Copy that. I reviewed that article and I understand what needs to be done. Estimate at 1 day.

**Comment by jaswrks** [comment]
![2016-11-19_06-49-21](https://cloud.githubusercontent.com/assets/1563559/20456543/01eece76-ae25-11e6-8a82-033483ea1dfd.png)

---

![2016-11-19_06-49-49](https://cloud.githubusercontent.com/assets/1563559/20456515/80866e20-ae24-11e6-9901-2a469c2a38ea.png)

---

![2016-11-19_06-50-24](https://cloud.githubusercontent.com/assets/1563559/20456513/8082691a-ae24-11e6-98ca-4923ae288614.png)

---

![2016-11-19_06-52-16](https://cloud.githubusercontent.com/assets/1563559/20456527/bf709854-ae24-11e6-8cbd-0993b68c3f37.png)

---

![2016-11-19_07-27-14](https://cloud.githubusercontent.com/assets/1563559/20456770/a4d0e5d0-ae29-11e6-92fd-7697b54eb189.png)

**Comment by jaswrks** [comment]
Referencing KBA draft: https://wpsharks.com/?post_type=kb_article&p=3073&preview=true
https://wpsharks.com/r/woocommerce-intercom-pro-personal-access-token-instructions

**Comment by jaswrks** [comment]
Next Release Changelog:
- **Compatibility:** Deprecating API Key setting for Intercom in favor of a Personal Access Token. There is now a configuration field under: **WP Dashboard → WooCommerce → Intercom** settings where you can supply a Personal Access Token for API calls to Intercom. Use the instructions provided in this area to generate and fill-in your Personal Access Token. See [Issue #20](https://github.com/websharks/woocommerce-intercom-pro/issues/20).
  
  _**Note:** If you were previously using an Intercom API Key, it will continue to work, for now; but please provide a Personal Access Token to avoid problems in future releases of this plugin._

**Comment by jaswrks** [comment]
Tagging as partial completion. Pending review by @raamdev and publication of [this KBA](https://wpsharks.com/?post_type=kb_article&p=3073&preview=true).

**Comment by renzms** [comment]
@raamdev 

### Update confirmed as working.

Setup WooCommerce Intercom following instructions above in the draft KBA.

Tested using:
- **WP Sharks Core Version 161026.47592**
- **WooCommerce Intercom Pro Version 161124.6961-RC**
- **WooCommerce Version 2.6.8**

No bugs here 👍

**Comment by jaswrks** [comment]
@raamdev @kristineds We could consider adding the Knowledge Base tab to this product page now that we have KBAs for this plugin: https://wpsharks.com/product/woocommerce-intercom-pro

**Comment by kristineds** [comment]
@jaswsinc @raamdev That KB tab has been added. https://wpsharks.com/product/woocommerce-intercom-pro

**Comment by raamdev** [comment]
**WooCommerce Intercom Pro v161209.85885** has been released and includes changes from this GitHub Issue. See the [changelog](https://wpsharks.com/product/woocommerce-intercom-pro/changelog) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#20).
