### ISSUE TITLE
Can't activate the plugin

### ISSUE THREAD

**Issue by tinof** [websharks/woocommerce-intercom-pro#21]
While trying to activate the plugin, I get the following error message:

Warning: require(/***/wp-content/plugins/woocommerce-intercom-pro-160909.7530/src/vendor/websharks/wp-php-rv/src/includes/check.php): failed to open stream: No such file or directory in /***/wp-content/plugins/woocommerce-intercom-pro-160909.7530/plugin.php on line 27 Fatal error: require(): Failed opening required '/***/wp-content/plugins/woocommerce-intercom-pro-160909.7530/src/vendor/websharks/wp-php-rv/src/includes/check.php' (include_path='.:/usr/share/php') in /***/wp-content/plugins/woocommerce-intercom-pro-160909.7530/plugin.php on line 27

Ubuntu 16.04, EasyEngine stack (Nginx, Redis, PHP7).

**Comment by jaswrks** [comment]
@tinof If you downloaded the plugin from the GitHub repo, you may have been using a copy that was not in a fully 'built' state. Please download the distributable ZIP file from: https://wpsharks.com/product/woocommerce-intercom-pro
