### ISSUE TITLE
Feature Request: Origin Site/URI

### ISSUE THREAD

**Issue by jaswrks** [websharks/woocommerce-intercom-pro#22]
Add the following fields to the JS Snippet:

```
'wp_site' => c::clip(home_url('/'), 255),
'wp_uri'  => c::midClip(c::currentUri(), 255),
```

**Comment by jaswrks** [comment]
Next Release Changelog:
- Adding `wp_site` and `wp_uri` fields to JS Snippet to make it easier for support representatives to identify the origin of a customer request; e.g., whenever a single Intercom account is being used to support more then one WordPress installation, or multiple child sites/domains in a Multisite Network. See [Issue #22](https://github.com/websharks/woocommerce-intercom-pro/issues/22).

**Comment by renzms** [comment]
@raamdev 

### Enhancement confirmed as working.

Tested using:
- **WP Sharks Core Version 161026.47592**
- **WooCommerce Intercom Pro Version 161124.6961-RC**
- **WooCommerce Version 2.6.8**

No bugs here 👍 

![screen shot 2016-11-28 at 10 09 08 pm](https://cloud.githubusercontent.com/assets/13220018/20671199/5b0a2a52-b5b7-11e6-9b30-e66cdbb6262b.png)

**Comment by jaswrks** [comment]
@renzms Thank you.

@raamdev I'm seeing room for improvement here and it might be worth us holding the next release for if we all agree.

## Problems

![2016-11-28_12-44-25](https://cloud.githubusercontent.com/assets/1563559/20687299/71476d24-b568-11e6-8c13-41a08e7421c4.png)

- `wp_site`, as it exists, includes the `scheme://` which leaves the potential for `http://` and `https://` variations to accumulate on the Intercom side, which may result in confusion and/or inaccurate search results when filtering by this field in Intercom.

- `wp_uri` does not include the domain, which prevents the field value from becoming clickable. So it's not possible to click that field value and be taken to the underlying URL, which would be somewhat useful since this field is all about identifying where the customer was at when they were seeking assistance.

## Suggested Changes

- `wp_site` could be renamed to `wp_home_url` and be forced to contain a scheme matching that of the default scheme for the site and not the _current_ scheme the customer landed on.

- `wp_uri` could be changed to `wp_current_url` and include the full URL of the current page.

- Also suggest adding `wp_network_home_url` whenever the plugin is running on a multisite network. This would identify the current network the request came from, in addition to `wp_home_url` which would identify the current child site in a such a scenario.

- Also suggest renaming `wp_user_edit` to `wp_user_edit_url`

**Comment by jaswrks** [comment]
## Updated Changelog

- **Enhancement:** Adding `wp_home_url` and `wp_network_home_url` fields to JS Snippet to make it easier for support representatives to identify the origin of a customer request; e.g., whenever a single Intercom account is being used to support more then one WordPress installation, or multiple child sites/domains in a Multisite Network. See [Issue #22](https://github.com/websharks/woocommerce-intercom-pro/issues/22).

- **Intercom `user_id`:** This release changes the way an Intercom `user_id` is generated. Instead of just the WP User ID, the Intercom `user_id` is now formulated in a way that allows a single Intercom account to be used for multiple installations of WordPress. The `user_id` sent to Intercom is now made up of two parts. 1. A hash of the current WordPress `home_url()` (normalized). 2. The current user's WordPress ID (or, in the case of guest checkout, an `e-`, followed by a hash of the user's email address). The final `user_id` becomes: `[location hash].[user ID]`; e.g., `3610a686.123`, `3610a686.e-9943c993` (guest).

- **New People Attribute:** This release adds a new People Attribute by the name of `wp_user_id`, giving support reps. the ability to track WP User IDs in Intercom.

**Comment by jaswrks** [comment]
Additional changelog entry:

- **New Filter:** A new filter has been exposed: `js_snippet_attrs`. This allows a developer to add their own custom attributes; above and beyond what is already defined by WooCommerce Intercom Pro itself.

**Comment by jaswrks** [comment]
Additional changelog entry:

- **Compatibility:** Adding support and compatibility with WPML's `ICL_LANGUAGE_CODE` so the Intercom messenger will always be displayed in an appropriate language.

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Updates for additional details for Intercom users working as intended.

> Enhancement: Adding wp_home_url and wp_network_home_url fields to JS Snippet to make it easier for support representatives to identify the origin of a customer request; e.g., whenever a single Intercom account is being used to support more then one WordPress installation, or multiple child sites/domains in a Multisite Network. See Issue #22.
> 
> Intercom user_id: This release changes the way an Intercom user_id is generated. Instead of just the WP User ID, the Intercom user_id is now formulated in a way that allows a single Intercom account to be used for multiple installations of WordPress. The user_id sent to Intercom is now made up of two parts. 1. A hash of the current WordPress home_url() (normalized). 2. The current user's WordPress ID (or, in the case of guest checkout, an e-, followed by a hash of the user's email address). The final user_id becomes: [location hash].[user ID]; e.g., 3610a686.123, 3610a686.e-9943c993 (guest).
> 
> New People Attribute: This release adds a new People Attribute by the name of wp_user_id, giving support reps. the ability to track WP User IDs in Intercom.


**Logged In User**
![screen shot 2016-12-06 at 12 26 34 am](https://cloud.githubusercontent.com/assets/13220018/20892900/dd7f01b8-bb4a-11e6-85a1-f384d6208919.png)


**Guest User**
![screen shot 2016-12-06 at 12 26 58 am](https://cloud.githubusercontent.com/assets/13220018/20892896/d9fbbe00-bb4a-11e6-9781-8e0a3bdbcf1c.png)

**Comment by raamdev** [comment]
**WooCommerce Intercom Pro v161209.85885** has been released and includes changes from this GitHub Issue. See the [changelog](https://wpsharks.com/product/woocommerce-intercom-pro/changelog) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#22).
