### ISSUE TITLE
SyntaxError: Unexpected token F in JSON at position 1

### ISSUE THREAD

**Issue by raamdev** [websharks/woocommerce-intercom-pro#4]
When placing an order:

![2016-09-19_22-41-55](https://cloud.githubusercontent.com/assets/53005/18655873/5b1d539a-7eba-11e6-8b37-539308bfb562.png)

**Comment by jaswrks** [comment]
```
[24-Sep-2016 06:45:36 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WC_Order::get_currency() in /app/src/wp-content/plugins/woocommerce-intercom-pro/src/includes/classes/Utils/Events.php:89
Stack trace:
#0 /app/src/wp-content/plugins/woocommerce-intercom-pro/src/includes/classes/Utils/Events.php(64): WebSharks\WpSharks\WooCommerceIntercom\Pro\Classes\Utils\Events->eventCreate(2854)
#1 /app/src/wp-includes/plugin.php(524): WebSharks\WpSharks\WooCommerceIntercom\Pro\Classes\Utils\Events->onWcOrderStatusChanged(2854, 'pending', 'completed')
#2 /app/src/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(2396): do_action('woocommerce_ord...', 2854, 'pending', 'completed')
#3 /app/src/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(2491): WC_Abstract_Order->update_status('completed')
#4 /app/src/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php(513): WC_Abstract_Order->payment_complete('ch_18x9ukLcnmSk...')
#5 /app/src/wp-content/plugins/woocommerce-gateway-stripe/ in /app/src/wp-content/plugins/woocommerce-intercom-pro/src/includes/classes/Utils/Events.php on line 89
```

**Comment by jaswrks** [comment]
- **Bug Fix:** Call to undefined method `WC_Order::get_currency()` should be `get_order_currency()`. Reported by @raamdev in [this GitHub issue](https://github.com/websharks/woocommerce-intercom-pro/issues/4).

**Comment by renzms** [comment]
@raamdev 

### Fixed confirmed as working.

Tested using:
- **WP Sharks Core Version 161026.47592**
- **WooCommerce Intercom Pro Version 161124.6961-RC**
- **WooCommerce Version 2.6.8**

No bugs here 👍

**Comment by raamdev** [comment]
**WooCommerce Intercom Pro v161209.85885** has been released and includes changes from this GitHub Issue. See the [changelog](https://wpsharks.com/product/woocommerce-intercom-pro/changelog) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#4).
