### ISSUE TITLE
Compat: Support Email Address if User ID Missing

### ISSUE THREAD

**Issue by jaswrks** [websharks/woocommerce-intercom-pro#6]
In the case of guest checkout, support email addresses in event reporting.
https://github.com/websharks/woocommerce-intercom-pro/blob/160909.7530/src/includes/classes/Utils/Events.php#L175

**Comment by jaswrks** [comment]
- Adding support for guest checkout events that track a customer by email address instead of by user ID. Closes [this GitHub issue](https://github.com/websharks/woocommerce-intercom-pro/issues/6).

**Comment by renzms** [comment]
@raamdev @jaswsinc 

### Bug Found

At checkout when purchasing as a guest user and adding Billing Details an error appears:

![screen shot 2016-11-28 at 10 02 45 pm](https://cloud.githubusercontent.com/assets/13220018/20670975/6dfc434e-b5b6-11e6-9c14-41502f541263.png)


Tested using:
- **WP Sharks Core Version 161026.47592**
- **WooCommerce Intercom Pro Version 161124.6961-RC**
- **WooCommerce Version 2.6.8**

### Steps to reproduce

- Setup WooCommerce and test products
- Purchase test product as a logged-out visitor
- Enter Billing Details and leave `create account` **unchecked** at checkout
- The following page shows the error:

```
Client error: `POST https://api.intercom.io/events` resulted in a `404 Not Found` response: {"type":"error.list","request_id":"aolcu4fj6sdf568g2kkg","errors":[{"code":"not_found","message":"User Not Found"}]}
```

**Comment by jaswrks** [comment]
@renzms Thank you. I'm researching this now. This may explain another problem I'm seeing at wpsharks.com that I haven't been able to explain as of yet.

**Comment by jaswrks** [comment]
Referencing: https://github.com/intercom/intercom-php/issues/185

**Comment by jaswrks** [comment]
- **Bug Fix:** Before a new Event is generated to track a user's Order or Subscription status on the Intercom side, a new API call is now made to ensure that a matching User does in fact exist on the Intercom side before an Event is created. This corrects a problem reported in the previous release that resulted in an error during checkout: `User Not Found`. See [Issue #6](https://github.com/websharks/woocommerce-intercom-pro/issues/6#issuecomment-263278631)

**Comment by renzms** [comment]
@jaswsinc @raamdev 

### Bug fix confirmed as working in latest update 👍 

>**WP Front End completes order normally:**

>>![screen shot 2016-12-06 at 12 07 18 am](https://cloud.githubusercontent.com/assets/13220018/20892369/f465bb58-bb48-11e6-958c-48148f12185b.png)
>
>
>
>**User is then created in Intercom Dashboard:**

>>![screen shot 2016-12-06 at 12 13 21 am](https://cloud.githubusercontent.com/assets/13220018/20892386/06c7ecc6-bb49-11e6-894d-ae9a07418d5f.png)

**Comment by jaswrks** [comment]
@renzms Thank you :-)

**Comment by raamdev** [comment]
**WooCommerce Intercom Pro v161209.85885** has been released and includes changes from this GitHub Issue. See the [changelog](https://wpsharks.com/product/woocommerce-intercom-pro/changelog) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#6).
